version: "2.1"
services:
  node:
    image: "node:18"
    user: "root"
    ports:
      - 8650:9100
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
      - /root/.ssh:/root/.ssh
    privileged: true
    command: sh ./start.sh
